# Generated by Django 5.1.2 on 2024-11-07 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iotdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.JSONField()),
                ('iot_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.iotdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
