# Generated by Django 5.1.2 on 2024-11-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iotdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdevice',
            old_name='user',
            new_name='owner',
        ),
    ]
