# Generated by Django 5.1.2 on 2024-11-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_devicevalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicevalue',
            old_name='iot_device',
            new_name='device',
        ),
    ]
