# Generated by Django 5.1.3 on 2024-11-18 09:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_devicevalue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevalue',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.image_file_path),
        ),
    ]
